Increase number of sections in object file on MSVC platforms
The new QUIC unit tests triggered msvc error C1128 due to excessive
number of sections in generated .obj files. Our msvc toolchain does
not detect msvs_settings block in gyps files like src/net.gyp so I'm
increasing the section number for debug and devel builds on win32 and
xb1.

b/135474776

Change-Id: Iae5e709a312881c00b08fa173021c5ad06023bbd

Former-commit-id: fe80b4c94a914fd72893349c1f8fff15a01fd1dc