Fix for Xbox not liking the constexpr declaration.
This stops using constexpr to avoid the compilation error:
error C2131: expression did not evaluate to a constant

b/274832572

Change-Id: I12148c567fca085ffbb08debda3fbbda9fd41099
(cherry picked from commit a8cf1dd53809377672dc4f1257e3a210bc08b71b)
NOKEYCHECK=True
GitOrigin-RevId: b26845d67173a40a745aabecd1395ae0081f7b23

Former-commit-id: 9f9a7c9677d5689f5a3883d492d2c5db0a39c76e