Remove the unused function 'DebugConsoleModeIntToString' .
The unused function was causing a build error:
../../cobalt/browser/debug_console.cc:60:13: error: unused function 'DebugConsoleModeIntToString' [-Werror,-Wunused-function]
Fixed it by removing it.

b/139460185

Change-Id: I1a2df4fee037aadc3300aed85c5ff8f070020436
(cherry picked from commit 25671ad5787b28792e0ea6d5c97f09637be6dea5)

Former-commit-id: f5d1ceedd495f1f285c1a7b25bdf42e799fd1402