Revert "Support webdriver element screenshot command."
This reverts commit 3a67328c7b0bcd858264a81818937c4c5d8ab5b7.

Reason for revert: Breaks layout_tests

../../cobalt/layout_tests/layout_tests.cc:111:54: error: no matching function for call to 'SnapshotURL'

Change-Id: Id2bc572e409c608c0d2e91bdc8979829374611c5

Former-commit-id: 788702cbdd3a5a4b0a08706463bbe6947d2be47c