Revert "[NX] SbPlayerTest.MultiPlayer fix"
This reverts commit 3296ce1f53e01112ef9440f86dcc638ff1469346.

Reason for revert: This CL breaks the Android build:
starboard/android/shared/player_create.cc:104:25: error: calling a private constructor of class 'SbPlayerPrivate'

Change-Id: I26455d1f8aa7a251b9a49fe5d990facb036b5bc2

Former-commit-id: c07fd73d1b4d38d1360c1092b56ba1fe06218b3c