Revert "Support webdriver element screenshot command."
This reverts commit 3a67328c7b0bcd858264a81818937c4c5d8ab5b7.

Reason for revert: Breaks layout_tests

../../cobalt/layout_tests/layout_tests.cc:111:54: error: no matching function for call to 'SnapshotURL'

Change-Id: Id2bc572e409c608c0d2e91bdc8979829374611c5

Former-commit-id: db5f9cb57d864ea2644f5b8f12ee04850a999664